import React from 'react';
import AdminScrapeSitesSection from '../../../features/admin/components/AdminScrapeSitesSection';
import AdminScraperControlSection from '../../../features/admin/components/AdminScraperControlSection';
import AdminSiteSuggestionsSection from '../../../features/admin/components/AdminSiteSuggestionsSection';

export default function AdminScraperPanel({
  fetchScraperControl,
  filteredSites,
  editingSiteId,
  formatDate,
  formatDateTime,
  formatDuration,
  formatEvidenceList,
  formatScraperRunType,
  formatSiteSuggestionStatus,
  handleAcceptSiteSuggestion,
  handleSaveScraperConfig,
  handleScraperIntervalChange,
  handleScraperMaxListingAgeChange,
  handleStartListingCleaner,
  handleStartScraper,
  handleStartSiteDiscovery,
  handleStopScraper,
  handleToggleSiteStatus,
  handleUpdateSiteSuggestionStatus,
  openCreateSitePanel,
  requestDeleteSite,
  scraperControl,
  scraperControlError,
  scraperControlLoading,
  scraperControlMessage,
  scraperCurrentCommandLabel,
  scraperEtaLabel,
  scraperIntervalDays,
  scraperIntervalDirty,
  scraperIsEnabled,
  scraperIsRunning,
  scraperMaxListingAgeYears,
  scraperProgressPercent,
  scraperProgressSteps,
  scraperRecentLog,
  scraperRunTypeLabel,
  scraperStatusClassName,
  scraperStatusLabel,
  scraperSubmitting,
  setSiteSearch,
  setSiteStatusFilter,
  setSiteSuggestionStatusFilter,
  siteDiscoverySubmitting,
  siteError,
  siteFormMessage,
  siteLoading,
  siteSearch,
  siteStatusFilter,
  siteSubmitting,
  siteSuggestionError,
  siteSuggestionLoading,
  siteSuggestionMessage,
  siteSuggestionStatusFilter,
  siteSuggestionSubmittingId,
  siteSuggestionTotals,
  siteSuggestions,
  siteTotals,
  startEditSite,
  statusFilterOptions,
  suggestionStatusFilterOptions,
}) {
  return (
    <div className="admin-content-grid admin-content-single">
      <section className="admin-analytics-column admin-sites-column">
        <AdminScraperControlSection
          scraperControl={scraperControl}
          scraperControlLoading={scraperControlLoading}
          scraperControlError={scraperControlError}
          scraperControlMessage={scraperControlMessage}
          scraperSubmitting={scraperSubmitting}
          scraperIntervalDays={scraperIntervalDays}
          scraperMaxListingAgeYears={scraperMaxListingAgeYears}
          scraperIntervalDirty={scraperIntervalDirty}
          scraperStatusClassName={scraperStatusClassName}
          scraperStatusLabel={scraperStatusLabel}
          scraperIsRunning={scraperIsRunning}
          scraperIsEnabled={scraperIsEnabled}
          scraperProgressPercent={scraperProgressPercent}
          scraperProgressSteps={scraperProgressSteps}
          scraperRunTypeLabel={scraperRunTypeLabel}
          scraperEtaLabel={scraperEtaLabel}
          scraperCurrentCommandLabel={scraperCurrentCommandLabel}
          scraperRecentLog={scraperRecentLog}
          siteTotals={siteTotals}
          handleScraperIntervalChange={handleScraperIntervalChange}
          handleScraperMaxListingAgeChange={handleScraperMaxListingAgeChange}
          handleSaveScraperConfig={handleSaveScraperConfig}
          handleStartScraper={handleStartScraper}
          handleStartListingCleaner={handleStartListingCleaner}
          handleStopScraper={handleStopScraper}
          fetchScraperControl={fetchScraperControl}
          formatDateTime={formatDateTime}
          formatDuration={formatDuration}
          formatScraperRunType={formatScraperRunType}
        />
        <AdminSiteSuggestionsSection
          suggestionStatusFilterOptions={suggestionStatusFilterOptions}
          siteSuggestions={siteSuggestions}
          siteSuggestionTotals={siteSuggestionTotals}
          siteSuggestionStatusFilter={siteSuggestionStatusFilter}
          setSiteSuggestionStatusFilter={setSiteSuggestionStatusFilter}
          siteSuggestionLoading={siteSuggestionLoading}
          siteSuggestionError={siteSuggestionError}
          siteSuggestionMessage={siteSuggestionMessage}
          siteSuggestionSubmittingId={siteSuggestionSubmittingId}
          siteDiscoverySubmitting={siteDiscoverySubmitting}
          handleStartSiteDiscovery={handleStartSiteDiscovery}
          handleAcceptSiteSuggestion={handleAcceptSiteSuggestion}
          handleUpdateSiteSuggestionStatus={handleUpdateSiteSuggestionStatus}
          formatSiteSuggestionStatus={formatSiteSuggestionStatus}
          formatEvidenceList={formatEvidenceList}
          formatDate={formatDate}
        />
        <AdminScrapeSitesSection
          statusFilterOptions={statusFilterOptions}
          filteredSites={filteredSites}
          siteSearch={siteSearch}
          setSiteSearch={setSiteSearch}
          siteStatusFilter={siteStatusFilter}
          setSiteStatusFilter={setSiteStatusFilter}
          siteFormMessage={siteFormMessage}
          siteError={siteError}
          siteLoading={siteLoading}
          siteSubmitting={siteSubmitting}
          editingSiteId={editingSiteId}
          openCreateSitePanel={openCreateSitePanel}
          handleToggleSiteStatus={handleToggleSiteStatus}
          startEditSite={startEditSite}
          requestDeleteSite={requestDeleteSite}
          formatDate={formatDate}
        />
      </section>
    </div>
  );
}
