BOT_NAME = "real_estate_scraper"

SPIDER_MODULES = ["real_estate_scraper.spiders"]
NEWSPIDER_MODULE = "real_estate_scraper.spiders"

ADDONS = {}

import os
ROBOTSTXT_OBEY = True

CRAWL_PROFILES = {
    "fast_stable": {
        "CONCURRENT_REQUESTS": 24,
        "CONCURRENT_REQUESTS_PER_DOMAIN": 10,
        "DOWNLOAD_DELAY": 0.1,
        "AUTOTHROTTLE_ENABLED": True,
        "AUTOTHROTTLE_START_DELAY": 0.1,
        "AUTOTHROTTLE_MAX_DELAY": 3.0,
        "AUTOTHROTTLE_TARGET_CONCURRENCY": 6.0,
    },
    "structured_large": {
        "CONCURRENT_REQUESTS": 16,
        "CONCURRENT_REQUESTS_PER_DOMAIN": 8,
        "DOWNLOAD_DELAY": 0.2,
        "AUTOTHROTTLE_ENABLED": True,
        "AUTOTHROTTLE_START_DELAY": 0.2,
        "AUTOTHROTTLE_MAX_DELAY": 5.0,
        "AUTOTHROTTLE_TARGET_CONCURRENCY": 4.0,
    },
    "fragile": {
        "CONCURRENT_REQUESTS": 8,
        "CONCURRENT_REQUESTS_PER_DOMAIN": 4,
        "DOWNLOAD_DELAY": 0.45,
        "AUTOTHROTTLE_ENABLED": True,
        "AUTOTHROTTLE_START_DELAY": 0.5,
        "AUTOTHROTTLE_MAX_DELAY": 8.0,
        "AUTOTHROTTLE_TARGET_CONCURRENCY": 1.5,
    },
}

DEFAULT_CRAWL_PROFILE = os.getenv("SCRAPER_CRAWL_PROFILE", "fast_stable").strip().lower()
if DEFAULT_CRAWL_PROFILE not in CRAWL_PROFILES:
    DEFAULT_CRAWL_PROFILE = "fast_stable"

ACTIVE_CRAWL_PROFILE = CRAWL_PROFILES[DEFAULT_CRAWL_PROFILE]

CONCURRENT_REQUESTS = ACTIVE_CRAWL_PROFILE["CONCURRENT_REQUESTS"]
CONCURRENT_REQUESTS_PER_DOMAIN = ACTIVE_CRAWL_PROFILE["CONCURRENT_REQUESTS_PER_DOMAIN"]
DOWNLOAD_DELAY = ACTIVE_CRAWL_PROFILE["DOWNLOAD_DELAY"]
RANDOMIZE_DOWNLOAD_DELAY = True

EXTENSIONS = {
    "real_estate_scraper.extensions.ActiveScrapeSiteGuardExtension": 100,
}
ITEM_PIPELINES = {
    "real_estate_scraper.pipelines.RawPipeline": 300,
}


AUTOTHROTTLE_ENABLED = ACTIVE_CRAWL_PROFILE["AUTOTHROTTLE_ENABLED"]

AUTOTHROTTLE_START_DELAY = ACTIVE_CRAWL_PROFILE["AUTOTHROTTLE_START_DELAY"]

AUTOTHROTTLE_MAX_DELAY = ACTIVE_CRAWL_PROFILE["AUTOTHROTTLE_MAX_DELAY"]

AUTOTHROTTLE_TARGET_CONCURRENCY = ACTIVE_CRAWL_PROFILE["AUTOTHROTTLE_TARGET_CONCURRENCY"]


RETRY_ENABLED = True
RETRY_TIMES = int(os.getenv("SCRAPER_RETRY_TIMES", "2"))
DOWNLOAD_TIMEOUT = int(os.getenv("SCRAPER_DOWNLOAD_TIMEOUT", "25"))
LOG_LEVEL = os.getenv("SCRAPER_LOG_LEVEL", "INFO")


FEED_EXPORT_ENCODING = "utf-8"
